spring:
  # 页面方面的配置
  thymeleaf:
    encoding: UTF-8
    # 热部署静态文件
    cache: false
    # 让thymeleaf解析标签没有闭合时通过
    mode: LEGACYHTML5

  # MVC相关配置
  mvc:
    # 配置ICO
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB